steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e

      # Run Makefile commands
      # make clean # Replace with your first make target
      # make build # Replace with your second make target

      apt-get update
      apt-get install -y curl make python3 python3-pip

      # Install Python dependencies
      python3 -m pip install --upgrade pip
      python3 -m pip install --ignore-installed -r requirements.txt
