# .pre-commit-config.yaml - Datest Pre-commit Hooks Configuration
# Copyright © 2025 Aitomatic, Inc. Licensed under the MIT License.

default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        exclude: ^mkdocs\.yml$
      - id: check-added-large-files
      - id: check-json
        exclude: ^\.ipynb$|\.vscode/settings\.json$
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: local
    hooks:
      - id: ruff-critical
        name: Critical lint checks (E722, F821)
        entry: ruff check datest/ tests/ --select=E722,F821
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: ruff-important
        name: Important lint checks (F841, B017)
        entry: ruff check datest/ tests/ --select=F841,B017
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: make-files-readonly
        name: Make files read-only
        entry: sh -c 'git ls-files examples/tutorials/** | xargs -r chmod -w'
        language: system
        pass_filenames: false
        always_run: true
        stages: [post-checkout, post-merge, post-rewrite]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix, --config=pyproject.toml]
      - id: ruff-format
        args: [--config=pyproject.toml]

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.9
    hooks:
      # Sync dependencies on checkout/merge/rebase
      - id: uv-sync
        stages: [post-checkout, post-merge, post-rewrite]
        args: [--all-extras]