#
# This is used if we are using "gcloud builds submit --config cloudbuild.yaml .", i.e., Cloud Build
#
steps:
- name: 'python:3.10-slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -ex

      apt-get update
      apt-get install -y curl make

      # Install Python dependencies
      python3 -m pip install --upgrade pip
      python3 -m pip install --ignore-installed -r requirements.txt
      python3 -m pip install --ignore-installed dist/openssm-0.1.5-py3-none-any.whl

      # Uncomment the lines below if you have make commands
      # make clean
      # make build
