#
# This is used if we are using 'gcloud app deploy', i.e., App Engine
#
runtime: python310  # or your current Python version

#entrypoint: gunicorn -b :$PORT app:app 
entrypoint: python3 app.py

automatic_scaling:
 target_cpu_utilization: 0.6
 min_instances: 1
 max_instances: 15

env_variables:
 OPENAI_API_KEY: _PATTERN_OPENAI_API_KEY_
 OPENAI_API_URL: _PATTERN_OPENAI_API_URL_

handlers:
- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js

- url: /static/images
  static_dir: static/images

- url: /.*
  script: auto
